services:
  # Production service - builds self-contained image
  todoist-mcp:
    build: .
    # Uncomment if your MCP server needs to expose a port
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Example environment variables (uncomment and set as needed)
      # - JWT_SECRET=your-jwt-secret-here
      # - TODOIST_API_TOKEN=your-api-token
    # Add any environment variables your app needs
    # env_file:
    #   - .env

  # Development service - uses volumes for hot reloading
  todoist-mcp-dev:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
      - bun_modules_dev:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "bun install && bun run dev"
    # ports:
    #   - "3000:3000"
    profiles:
      - dev

volumes:
  bun_modules_dev:
